DROP TABLE IF EXISTS cars;

CREATE TABLE
    IF NOT EXISTS cars (
        ID  SERIAL PRIMARY KEY,
        MODEL VARCHAR(255) NOT NULL,
        PRICE INT NOT NULL
    );

DROP TABLE IF EXISTS rents;

CREATE TABLE
    IF NOT EXISTS rents (
        ID  SERIAL PRIMARY KEY,
        CAR_ID INT NOT NULL,
        FROM_DATE TEXT  NOT NULL,
        TO_DATE TEXT  NOT NULL,
        RENTER_NAME VARCHAR(255) NOT NULL
    );