DROP TABLE IF EXISTS cars;

CREATE TABLE
    IF NOT EXISTS cars (
        ID  SERIAL PRIMARY KEY,
        MODEL VARCHAR(255) NOT NULL,
        PRICE INT NOT NULL,
        RENTED BOOLEAN NOT NULL DEFAULT FALSE,
        FROM_DATE TEXT,
        TO_DATE TEXT,
        RENTER_ID INT
    );

DROP TABLE IF EXISTS renters;

CREATE TABLE
    IF NOT EXISTS renters (
        ID  SERIAL PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL
    );