DROP TABLE IF EXISTS cars;

CREATE TABLE
    IF NOT EXISTS cars (
        ID  SERIAL PRIMARY KEY,
        MODEL VARCHAR(255) NOT NULL,
        PRICE INT NOT NULL,
        RENTED BOOLEAN NOT NULL DEFAULT FALSE,
        FROM_DATE DATE,
        TO_DATE DATE,
        USER_ID INT
    );

DROP TABLE IF EXISTS users;

CREATE TABLE
    IF NOT EXISTS users (
        ID  SERIAL PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL
    );